### ISSUE TITLE
Extra builddir for each app

### ISSUE THREAD

**Issue by hirschenberger** [code-lever/elixir-cmake#7]
Hi, I have an umbrella app with multiple apps that have cmake builds. ATM they conflict with each other, as there's only one build dir for all of them.
There's a [patch](https://github.com/wwww-wwww/elixir-cmake/commit/122e900bd94a2c3ac4b86dc83f074ea31e2b2f9c) in a fork that fixes the issue for me.
Could you maybe integrate it and release a new version to hex?

Thanks

**Comment by nickveys** [comment]
You bet!  Open up a pull request with that please and I can make a new release.

**Comment by kent-mcleod** [comment]
Hello, I also have had the same issue and have proposed https://github.com/code-lever/elixir-cmake/pull/8 as a solution.
